fluidRow(
  p(id = "text_ora_plots", "Please submit your configuration first and plot your table!"),
  shinyjs::hidden(
    div(id = "ora_plots_tabsetPanel",
        tabsetPanel(type = "tabs",
                    tabPanel("Bar plot - Gene Counts",
                            p(id = "ora_barplot1_text", "Processing..."),
                            plotOutput("barplot1", height = "600px")),
                    tabPanel("Bar plot - qscore",
                            p(id = "ora_barplot2_text", "Processing..."),                            
                            plotOutput("barplot2", height = "600px")),
                    tabPanel("Dot Plot",
                            p(id = "ora_dotplot_text", "Processing..."),                            
                            plotOutput("dotplot", height = "600px")),
                    tabPanel("Enrichment Map Plot",
                            p(id = "ora_emapplot_text", "Processing..."),                            
                            plotOutput("emapplot", height = "600px")),
                    tabPanel("Gene-Concept Network Plot",
                            p(id = "ora_cnetplot_text", "Processing..."),                            
                            plotOutput("cnetplot", height = "600px")),
                    tabPanel("HeatMap Plot",
                            p(id = "ora_heatplot_text", "Processing..."),                            
                            plotOutput("heatplot", height = "600px")),
                    tabPanel("Tree Plot",
                            p(id = "ora_treeplot_text", "Processing..."),                            
                            plotOutput("treeplot", height = "600px")),
                    tabPanel("UpSetPlot",
                            p(id = "ora_upsetplot_text", "Processing..."),                            
                            plotOutput("upsetplot")),
        )))
)